// <auto-generated />
namespace InventoryManagement.Web.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.0.0-20911")]
    public sealed partial class Database_Baseline : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(Database_Baseline));
        
        string IMigrationMetadata.Id
        {
            get { return "201602091027005_Database_Baseline"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
